using FreeDiskAnalyzer.Core.Models;

namespace FreeDiskAnalyzer.Models;

public sealed class SystemCleanupItem
{
    public required SystemCleanupCategory Category { get; init; }
    public required long SizeBytes { get; init; }

    // Both categories here are low risk: temp files are regenerated by
    // Windows/apps as needed, and Recycle Bin contents have already been
    // "deleted" once by the user, this just finishes that.
    public RiskLevel RiskLevel => RiskLevel.Low;
}
