using FreeDiskAnalyzer.Core.Models;

namespace FreeDiskAnalyzer.Models;

public sealed class SystemCleanupItem
{
    public required SystemCleanupCategory Category { get; init; }
    public required long SizeBytes { get; init; }

    // Temp files: low risk, regenerated by Windows/apps as needed, and
    // deleted to the Recycle Bin so still recoverable. Recycle Bin itself:
    // medium risk, emptying it is permanent, and someone may have put
    // something there meaning to restore it later.
    public RiskLevel RiskLevel => Category switch
    {
        SystemCleanupCategory.TempFiles => RiskLevel.Low,
        SystemCleanupCategory.RecycleBin => RiskLevel.Medium,
        _ => RiskLevel.Medium
    };
}
